nelmio_api_doc:

    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)

    documentation:

        info:
            title: Bilemo Api
            description: API description for Bilemo App
            version: 1.0.0

        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Bearer: {TOKEN}, obtain by /api/login/client'
                name: Authorization
                in: header

        tags:
            - name: Authentication
              description: Get access to your token
            - name: Client
              description: Manager Client
            - name: Phone
              description: Manager Phone


        paths:
            /api/login/client:
                post:
                    tags:
                        - Authentication
                    summary: Client authentication.
                    parameters:
                        - in: body
                          name: body
                          required: true
                          description: Request payload must contain all informations.
                          schema:
                            $ref: "#/definitions/AuthenticationInput"
                    responses:
                        200:
                            description: OK
                            schema:
                                $ref: "#/definitions/JwtSuccessOutput"
                        400:
                            description: Bad Request. Check your request.
                        401:
                            description: Unauthorized. Bad credential.
                            schema:
                                $ref: "#/definitions/JwtErrorOutput"

            /api/clients:
                post:
                    tags:
                        - Client
                    summary: Client registration.
                    description: '##  Access for anonymous user'
                    parameters:
                        - in: body
                          name: body
                          required: true
                          description: Request payload must contain all informations.
                          schema:
                              $ref: "#/definitions/ClientInput"
                    responses:
                        201:
                            description: Created
                        400:
                            description: Bad Request. Check your request.

            /api/clients/{client_id}/users:
                post:
                    security:
                        - Bearer: []
                    tags:
                        - Client
                    summary: Create new user in client's user catalog.
                    description: '## Access for client'
                    parameters:
                        - in: path
                          name: client_id
                          required: true
                          type: string
                          description: The client unique identifier.
                        - in: body
                          name: body
                          required: true
                          description: Request payload must contain all informations
                          schema:
                              $ref: "#/definitions/UserInput"
                    responses:
                        201:
                            description: Created
                        400:
                            description: Bad Request. Check your request.
                        401:
                            description: Unauthorized. Your token is expired, please renew it.
                        403:
                            description: Forbidden. Missing token | Invalid token | Client has no access

                get:
                    security:
                        - Bearer: []
                    tags:
                        - Client
                    summary: Get all users in client's user catalog.
                    description: '## Access for client'
                    parameters:
                        - in: path
                          name: client_id
                          required: true
                          type: string
                          description: The client unique identifier.
                    responses:
                        200:
                            description: OK
                            schema:
                                type: array
                                items:
                                    $ref: "#/definitions/ListUserOutput"
                        204:
                            description: NO CONTENT. Client's user catalog is empty
                        401:
                            description: Unauthorized. Your token is expired, please renew it.
                        403:
                            description: Forbidden. Missing token | Invalid token | Client has no access


        definitions:
            AuthenticationInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true

            JwtErrorOutput:
                type: object
                properties:
                    code:
                        type: integer
                        required: true
                    message:
                        type: string
                        required: true

            JwtSuccessOutput:
                type: object
                properties:
                    token:
                        type: string
                        required: true
                    client:
                        type: object
                        required: true
                        properties:
                            id:
                                type: string
                                required: true

            ClientInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true

            UserInput:
                type: object
                properties:
                    firstName:
                        type: string
                        required: true
                    lastName:
                        type: string
                        required: true
                    phoneNumber:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true

            ShowPhoneOutput:
                type: array
                items:
                    $ref: "#/definitions/ShowPhoneItemsOutput"
            ShowPhoneItemsOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    description:
                        type: string
                        required: true
                    price:
                        type: integer
                        required: true
                    stock:
                        type: integer
                        required: true
                    created_at:
                        type: string
                        format: date-time
                        required: true
                    updated_at:
                        type: string
                        format: date-time
                        required: false
                    _links:
                        type: object
                        properties:
                            self:
                                type: object
                                required: true
                                properties:
                                    href:
                                        type: string
                                        required: true
                    _embedded:
                        type: object
                        properties:
                            maker:
                                type: object
                                required: true
                                properties:
                                    id:
                                        type: string
                                        required: true
                                    name:
                                        type: string
                                        required: true

            ListUserOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    first_name:
                        type: string
                        required: true
                    last_name:
                        type: string
                        required: true
                    _links:
                        type: object
                        required: true
                        properties:
                            self:
                                type: object
                                required: true
                                properties:
                                    href:
                                        type: string
                                        required: true
                            delete:
                                type: object
                                required: true
                                properties:
                                    href:
                                        type: string
                                        required: true
                            add:
                                type: object
                                required: true
                                properties:
                                    href:
                                        type: string
                                        required: true

            NotFoundOutput:
                type: object
                properties:
                    message:
                        type: string
                        required: true
