nelmio_api_doc:
    documentation:
        info:
            title: Bilemo Api
            description: API description for Bilemo App
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {TOKEN}, obtain by /api/login/client'
                name: Authorization
                in: header
        definitions:
            AddUserInput:
                type: array
                items:
                    $ref: "#/definitions/AddUserItemsInput"
            AddUserItemsInput:
                type: object
                properties:
                    firstName:
                        type: string
                        required: true
                    lastName:
                        type: string
                        required: true
                    phoneNumber:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true

            AddClientInput:
                type: array
                items:
                    $ref: "#/definitions/AddClientItemsInput"
            AddClientItemsInput:
                type: object
                properties:
                    username:
                        type: string
                        required: true
                    password:
                        type: string
                        required: true
                    email:
                        type: string
                        required: true

            ShowPhoneOutput:
                type: array
                items:
                    $ref: "#/definitions/ShowPhoneItemsOutput"
            ShowPhoneItemsOutput:
                type: object
                properties:
                    id:
                        type: string
                        required: true
                    name:
                        type: string
                        required: true
                    description:
                        type: string
                        required: true
                    price:
                        type: integer
                        required: true
                    stock:
                        type: integer
                        required: true
                    created_at:
                        type: string
                        format: date-time
                        required: true
                    updated_at:
                        type: string
                        format: date-time
                        required: false
                    _links:
                        type: object
                        properties:
                            self:
                                type: object
                                required: true
                                properties:
                                    href:
                                        type: string
                                        required: true
                    _embedded:
                        type: object
                        properties:
                            maker:
                                type: object
                                required: true
                                properties:
                                    id:
                                        type: string
                                        required: true
                                    name:
                                        type: string
                                        required: true

            JwtErrorOutput:
                type: object
                properties:
                    code:
                        type: integer
                        required: true
                    message:
                        type: string
                        required: true

            NotFoundOutput:
                type: object
                properties:
                    message:
                        type: string
                        required: true


    areas:
        path_patterns:
            - ^/api(?!/doc$)
